# Generated by Django 5.0.9 on 2026-04-23 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customernote'),
        ('enquiries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='enquiry',
            name='enquiries_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='enquiry',
            name='enquiries_customer_idx',
        ),
        migrations.RenameIndex(
            model_name='enquiry',
            new_name='enquiries_status_3b38ab_idx',
            old_name='enquiries_status_idx',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='sm8_push_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='sm8_push_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='sm8_push_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='ai_confidence',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='ai_recommendation',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='customer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='customer_postcode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_enquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='source',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('referral', 'Referral'), ('google', 'Google'), ('facebook', 'Facebook'), ('checkatrade', 'Checkatrade'), ('phone', 'Phone'), ('other', 'Other')], default='website', max_length=30),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('NEEDS_MANUAL_REVIEW', 'Needs Manual Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['created_at'], name='enquiries_created_87e45c_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['customer_email'], name='enquiries_custome_173741_idx'),
        ),
        migrations.AddIndex(
            model_name='enquiry',
            index=models.Index(fields=['customer_phone'], name='enquiries_custome_e213a3_idx'),
        ),
    ]
