# Generated by Django 5.0.9 on 2026-04-17 09:54

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sm8_company_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('postcode', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('job_count', models.IntegerField(default=0)),
                ('last_job_date', models.DateField(blank=True, null=True)),
                ('last_job_type', models.CharField(blank=True, default='', max_length=100)),
                ('segments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('email_opt_out', models.BooleanField(default=False)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('heatshield_status', models.CharField(choices=[('active', 'Active'), ('lapsed', 'Lapsed'), ('cancelled', 'Cancelled'), ('none', 'None')], default='none', max_length=15)),
                ('sm8_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customers',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['segments'], name='customers_segments_gin'), models.Index(fields=['-last_job_date'], name='customers_last_job_idx'), models.Index(fields=['heatshield_status'], name='customers_hs_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sm8_job_uuid', models.UUIDField(unique=True)),
                ('sm8_company_uuid', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('job_address', models.TextField(blank=True, default='')),
                ('job_description', models.TextField(blank=True, default='')),
                ('job_type', models.CharField(blank=True, default='', max_length=100)),
                ('total_invoice_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('materials_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('quote_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('sm8_synced_at', models.DateTimeField(blank=True, null=True)),
                ('attributed_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributed_jobs', to='campaigns.campaign')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='customers.customer')),
            ],
            options={
                'db_table': 'jobs_cache',
                'indexes': [models.Index(fields=['customer'], name='jobs_customer_idx'), models.Index(fields=['status'], name='jobs_status_idx'), models.Index(fields=['-completed_date'], name='jobs_completed_idx'), models.Index(fields=['status', 'completed_date', 'total_invoice_amount'], name='jobs_kpi_composite_idx')],
            },
        ),
    ]
