# Generated by Django 5.0.9 on 2026-04-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcache',
            name='engineer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
