# Generated by Django 5.0.9 on 2026-04-17 09:54

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.IntegerField()),
                ('customer_ids', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), size=None)),
                ('scheduled_for', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('send_count', models.IntegerField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'campaign_batches',
            },
        ),
        migrations.CreateModel(
            name='CampaignEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('spam_complaint', 'Spam complaint'), ('unsubscribed', 'Unsubscribed')], max_length=20)),
                ('resend_email_id', models.CharField(blank=True, default='', max_length=255)),
                ('link_url', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'campaign_events',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('segment_filters', models.JSONField(blank=True, default=list)),
                ('recipient_count', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField()),
                ('from_name', models.CharField(default='Gareth — HeatGlow', max_length=100)),
                ('from_email', models.EmailField(default='gareth@heatglow.co.uk', max_length=254)),
                ('reply_to', models.EmailField(blank=True, default='', max_length=254)),
                ('campaign_type', models.CharField(choices=[('one_off', 'One-off'), ('automation_tier2', 'Automation tier 2')], default='one_off', max_length=25)),
                ('automation_trigger', models.CharField(blank=True, default='', max_length=100)),
                ('send_mode', models.CharField(choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled'), ('spread', 'Spread')], default='immediate', max_length=15)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('spread_days', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('failed', 'Failed')], default='draft', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_sent', models.IntegerField(default=0)),
                ('total_delivered', models.IntegerField(default=0)),
                ('total_opened', models.IntegerField(default=0)),
                ('total_clicked', models.IntegerField(default=0)),
                ('total_bounced', models.IntegerField(default=0)),
                ('attributed_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaigns',
            },
        ),
        migrations.CreateModel(
            name='CampaignAttribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('attributed_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'campaign_attributions',
            },
        ),
    ]
