# Generated by Django 5.0.9 on 2026-04-17 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignattribution',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='campaignattribution',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='customers.jobcache'),
        ),
        migrations.AddField(
            model_name='campaignbatch',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignevent',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignevent',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_events', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='campaignattribution',
            name='open_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaignevent'),
        ),
        migrations.AddConstraint(
            model_name='campaignevent',
            constraint=models.UniqueConstraint(condition=models.Q(('resend_email_id', ''), _negated=True), fields=('resend_email_id', 'event_type'), name='events_resend_idempotency'),
        ),
    ]
