# Generated by Django 5.0.9 on 2026-04-17 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automation', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationqueue',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_items', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='automationqueue',
            index=models.Index(condition=models.Q(('status__in', ['pending', 'failed'])), fields=['status', 'scheduled_for'], name='queue_poll_idx'),
        ),
    ]
